FROM openjdk:17-oracle
WORKDIR /app
COPY jars/ratingservice-0.0.1-SNAPSHOT.jar /app/ratingservice-0.0.1-SNAPSHOT.jar
EXPOSE 9095
CMD ["java", "-jar","-Dspring.profiles.active=grpc", "ratingservice-0.0.1-SNAPSHOT.jar"]
