FROM nginx:latest

# Remove default NGINX configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom NGINX configuration file
COPY api_gateway.conf /etc/nginx/conf.d/

# Expose ports
EXPOSE 80
