FROM openjdk:17-oracle
WORKDIR /app
COPY jars/collectorservice-0.0.1-SNAPSHOT.jar /app/collectorservice-0.0.1-SNAPSHOT.jar
EXPOSE 9096
CMD ["java", "-jar","-Dspring.profiles.active=grpc", "collectorservice-0.0.1-SNAPSHOT.jar"]
