FROM openjdk:17-oracle
WORKDIR /app
COPY jars/bankingservice-0.0.1-SNAPSHOT.jar /app/bankingservice-0.0.1-SNAPSHOT.jar
EXPOSE 9091
CMD ["java", "-jar","-Dspring.profiles.active=grpc", "bankingservice-0.0.1-SNAPSHOT.jar"]
