#Dockerfile-java
FROM openjdk:17-oracle
WORKDIR /app
COPY jars/financialcalcservice-0.0.1-SNAPSHOT.jar /app/financialcalcservice-0.0.1-SNAPSHOT.jar
EXPOSE 9092
CMD ["java", "-jar","-Dspring.profiles.active=grpc", "financialcalcservice-0.0.1-SNAPSHOT.jar"]
