FROM openjdk:17-oracle
WORKDIR /app
COPY jars/bankingservice-0.0.1-SNAPSHOT.jar /app/bankingservice-0.0.1-SNAPSHOT.jar
EXPOSE 9090
CMD ["java", "-jar","-Dspring.profiles.active=rest", "bankingservice-0.0.1-SNAPSHOT.jar"]
