#Dockerfile-java
FROM openjdk:17-oracle
WORKDIR /app
COPY jars/paymentservice-0.0.1-SNAPSHOT.jar /app/paymentservice-0.0.1-SNAPSHOT.jar
EXPOSE 9094
CMD ["java", "-jar","-Dspring.profiles.active=rest", "paymentservice-0.0.1-SNAPSHOT.jar"]
